FROM amazonlinux:2017.03.1.20170812 as base

ENV PATH=/env/bin:$PATH
ENV LC_LANG=en_GB.utf8
ENV LANG=en_GB.utf8

ADD . /service

WORKDIR /service
RUN yum -y install gcc python36 which
RUN alternatives --set python /usr/bin/python3.6
RUN pip install pipenv
RUN pipenv install -d